name: strava-gear
version: '0.1.0.0'
synopsis: Strava advanced gear tracker
maintainer: Tomáš Janoušek <tomi@nomi.cz>
copyright: (c) 2015-2017 Tomáš Janoušek
license: BSD3
github: liskin/strava-gear

default-extensions: NoImplicitPrelude
dependencies:
    - base
    - protolude
ghc-options:
    - -Wall

library:
    source-dirs: src
    dependencies:
        - blaze-html
        - bytestring
        - cereal
        - cereal-text
        - containers
        - cryptonite
        - data-default
        - esqueleto
        - exceptions
        - filepath
        - network-uri
        - persistent
        - persistent-sqlite
        - persistent-template
        - servant-auth-cookie
        - servant-blaze
        - servant-server
        - split
        - strive
        - tabular
        - text
        - time
        - transformers
        - wai
        - wai-app-static
        - warp

tests:
    hspec:
        main: hspec.hs
        source-dirs: test
        dependencies:
            - hspec
            - strava-gear
        ghc-options:
            - -threaded

executables:
    strava-gear-cmdline:
        main: strava-gear-cmdline.hs
        dependencies: [strava-gear]
        ghc-options:
            - -threaded

    strava-gear-web:
        main: strava-gear-web.hs
        dependencies: [strava-gear]
        ghc-options:
            - -threaded
