name: strava-gear
version: '0.1.0.0'
synopsis: Strava advanced gear tracker
maintainer: Tomáš Janoušek <tomi@nomi.cz>
copyright: (c) 2015-2017 Tomáš Janoušek
license: BSD3
github: liskin/strava-gear

default-extensions: NoImplicitPrelude
dependencies:
    - base
    - protolude
ghc-options:
    - -Wall

library:
    source-dirs: src
    dependencies:
        - aeson
        - containers
        - esqueleto
        - megaparsec
        - persistent
        - persistent-sqlite
        - persistent-template
        - scientific
        - split
        - strive
        - tabular
        - text
        - time

tests:
    hspec:
        main: hspec.hs
        source-dirs: test
        dependencies:
            - containers
            - heredoc
            - hspec
            - hspec-megaparsec
            - megaparsec
            - strava-gear
            - time
        ghc-options:
            - -threaded

executables:
    &default_executable
    dependencies: [strava-gear]
    ghc-options:
        - -threaded

executables:
    strava-gear-cmdline:
        <<: *default_executable
        main: strava-gear-cmdline.hs
