resolver: lts-3.20
flags: {}
packages:
- '.'
- location: ../strive
    #git: git://github.com/tfausak/strive.git
    #commit: c39704d5f008af42f5c3c2d5319476c7aa12e52d
  extra-dep: true
extra-deps:
- gpolyline-0.1.0.1
