resolver: lts-3.20
flags: {}
packages:
- '.'
- location:
    git: git://github.com/tfausak/strive.git
    commit: cfbd995dacafb1242482c0b6ce23826fad505338
  extra-dep: true
extra-deps:
- gpolyline-0.1.0.1
