resolver: lts-4.1
flags: {}
packages:
- '.'
- location:
    git: git://github.com/tfausak/strive.git
    commit: f5743fc44f92c7964b754a74ce103a4a1d21b711
  extra-dep: true
extra-deps:
- gpolyline-0.1.0.1
